### PR TITLE
fix: support for restoreV4

### LINKED ISSUE #138: Hatch not being added "Unsupported Product Found: restoreV4"
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest] Unsupported Product Found: restoreV4
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest] Configuring Hatch Devices:
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest]   Rest+ 2nd Gen: 1
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest]   Restore: 1
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest] Debug info for restoreV4 MasteBed Hatch:
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest] {
  "id": "***",
  "createDate": "2024-08-25 20:48:46",
  "updateDate": "2024-08-25 20:48:46",
  "macAddress": "***",
  "owner": true,
  "productDevice": {
    "id": 6184406,
    "createDate": "2023-12-08 01:51:55",
    "updateDate": "2024-10-10 10:46:50",
    "product": "restoreV4",
    "macAddress": "E4:65:B8:13:D7:B2",
    "memberId": 1317888,
    "name": "MasteBed Hatch",
    "hardwareVersion": "10.0.2",
    "firmwareVersion": "10.1.489",
    "targetedFirmwareVersion": null,
    "mandatory": false,
    "consumerMode": true,
    "iotCertificateId": "5c78393635483d83f1005d9090c0169a4f1508f3c69d46c50946203a28957cbf",
    "registrationDate": null,
    "replacementEmailSent": null,
    "deviceReturn": null,
    "replacement": null,
    "isFactory": false,
    "outOfWarranty": false,
    "warrantyDateString": null
  },
  "name": "MasteBed Hatch",
  "product": "restoreV4",
  "email": "***",
  "memberId": "***",
  "hardwareVersion": "10.0.2",
  "thingName": "***"
}
[10/10/2024, 9:00:03 AM] [homebridge-hatch-baby-rest] State for restoreV4 MasteBed Hatch:
[10/10/2024, 9:00:04 AM] [homebridge-hatch-baby-rest] {
  "env": "prod",
  "alarmsDisabled": false,
  "nightlightOn": false,
  "nightlightIntensity": 32780,
  "toddlerLockOn": false,
  "snoozeDuration": 540,
  "knockThreshold": 20,
  "knockDuration": 0,
  "activeTap": true,
  "knockAxis": 1,
  "current": {
    "srId": 0,
    "playing": "none",
    "step": 0,
    "color": {
      "id": 9998,
      "r": 0,
      "g": 0,
      "b": 0,
      "w": 0,
      "i": 16239,
      "duration": 0,
      "until": "indefinite"
    },
    "sound": {
      "id": 19998,
      "v": 29332,
      "mute": false,
      "url": "https://images.hatchbaby.com/content/sounds/noSound.wav",
      "duration": 0,
      "until": "indefinite"
    },
    "paused": false
  },
  "dataVersion": "20241009080700111",
  "sleepScene": {
    "srId": 0,
    "enabled": false
  },
  "timer": {
    "s": "2024-10-10 11:41:07",
    "d": 0
  },
  "streaming": {
    "status": "none"
  },
  "timezone": "America/Denver",
  "rF": {
    "v": "10.1.489",
    "i": true,
    "u": "https://firmware.hatchbaby.com/prod/restoreV4/restoreV4_DFU_10_1_489.json?f=g"
  },
  "deviceInfo": {
    "f": "10.1.489",
    "fR": 0,
    "hwVersion": "10.0.2",
    "powerStatus": 0,
    "sdCardVersionInfo": {
      "releaseDate": "unknown",
      "hashType": "md5",
      "hashCode": "0x00000000000000000000000000000000"
    }
  },
  "clock": {
    "i": 1211210137,
    "turnOffAt": "22:00:00",
    "turnOnAt": "07:00:00",
    "turnDimAt": "22:00:00",
    "turnBrightAt": "07:00:00",
    "flags": 32816,
    "turnOffMode": "never"
  },
  "toddlerLock": {
    "turnOffAt": "00:00:00",
    "turnOnAt": "00:00:00",
    "turnOnMode": "never"
  },
  "lucky": 0,
  "LDR": "RECV_FAIL",
  "LWTP": false,
  "debug": 0,
  "hwDebugFlags": 0,
  "logging": 37,
  "owned": true,
  "lastReset": "PowerOn_OtherWDT",
  "ota": {
    "status": "none",
    "downloadProgress": 0,
    "installProgress": 0
  },
  "touch": {
    "flags": 0,
    "poll_rate_hz": 0,
    "refire_delay_ms": 0,
    "refire_rate_hz": 0,
    "step_size": 0
  },
  "REX": {
    "lock": 692316220,
    "key": 0,
    "command": "none",
    "auth": 3856084876
  },
  "connected": true,
  "rssi": -52,
  "snooze": {
    "active": false,
    "startTime": ""
  }
}

### PR DESCRIPTION
**Pull request by jbryandev**
This PR adds support for "restoreV4" devices. Should close #138 and #104.

### CODE REVIEW

**Review by dgreif — APPROVED** [review]
Thanks for getting this added. I don't have one of these to test with, but I'll include it in the next beta release so folks can test it out

File: packages/shared/hatch-sleep-types.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ export const Product = {
   restMini: 'restMini',
   restore: 'restore',
   restoreIot: 'restoreIot',
+  restoreV4 = 'restoreV4',
```
Comment (dgreif) [inline packages/shared/hatch-sleep-types.ts:9]: I converted this an object instead of an enum so the syntax is slightly different now

```suggestion
  restoreV4: 'restoreV4',
```
